In [1]:
import numpy as np
import pandas as pd
import torch as torch

In [2]:
dataset=pd.read_csv('Z:/users/songyeon/DrugTargetIdentification/DepMap(22Q1)/CCLE_mutations.csv', low_memory=False)
info=pd.read_csv('Z:/users/songyeon/DrugTargetIdentification/DepMap(22Q1)/sample_info_PrimarySite.csv')

In [4]:
dataset

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,...,False,0.0,NaN,silent,118:0,NaN,NaN,10:0,118:0,18:0
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231276,DOCK11,139818,37,X,117810604,117810604,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231277,XIAP,331,37,X,123025155,123025157,+,In_Frame_Del,DEL,GAG,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231278,MAGEA10,4109,37,X,151304068,151304068,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN
1231279,IRAK1,3654,37,X,153283528,153283528,+,Missense_Mutation,SNP,G,...,False,2.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN
1231280,FLNA,2316,37,X,153583232,153583232,+,Silent,SNP,A,...,False,0.0,NaN,silent,22:0,NaN,NaN,NaN,NaN,NaN

In [5]:
dataset = dataset.drop(dataset[dataset.Entrez_Gene_Id == 0].index) #Entrez Gene ID가 0인 경우들을 제거 (invalid ID)

In [6]:
dataset

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,...,False,0.0,NaN,silent,118:0,NaN,NaN,10:0,118:0,18:0
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231276,DOCK11,139818,37,X,117810604,117810604,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231277,XIAP,331,37,X,123025155,123025157,+,In_Frame_Del,DEL,GAG,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231278,MAGEA10,4109,37,X,151304068,151304068,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN
1231279,IRAK1,3654,37,X,153283528,153283528,+,Missense_Mutation,SNP,G,...,False,2.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN
1231280,FLNA,2316,37,X,153583232,153583232,+,Silent,SNP,A,...,False,0.0,NaN,silent,22:0,NaN,NaN,NaN,NaN,NaN

In [11]:
len(pd.unique(dataset.Entrez_Gene_Id))#DepMap portal에 있는 gene 갯수보다 1개 작으면 됨

18783

In [10]:
dataset['Variant_Classification'].value_counts()

Missense_Mutation           696855
Silent                      351630
Splice_Site                  42376
Frame_Shift_Del              41170
Nonsense_Mutation            40094
Frame_Shift_Ins              24516
In_Frame_Del                  7686
De_novo_Start_OutOfFrame      4214
In_Frame_Ins                  3251
Start_Codon_SNP               1354
Nonstop_Mutation               922
Intron                         338
Stop_Codon_Del                 174
Start_Codon_Del                136
Stop_Codon_Ins                 128
Start_Codon_Ins                 92
IGR                             85
5'Flank                         72
3'UTR                           53
5'UTR                           31
Name: Variant_Classification, dtype: int64

In [28]:
dataset = dataset[dataset.Variant_Classification!='Silent']#Silent mutation 제거

In [29]:
dataset

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN
5,POU3F1,5453,37,1,38512139,38512139,+,Missense_Mutation,SNP,C,...,False,0.0,NaN,other non-conserving,NaN,NaN,NaN,NaN,NaN,10:4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231274,C8G,733,37,9,139839784,139839784,+,Frame_Shift_Del,DEL,T,...,False,0.0,NaN,damaging,25:17,NaN,NaN,NaN,NaN,NaN
1231276,DOCK11,139818,37,X,117810604,117810604,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231277,XIAP,331,37,X,123025155,123025157,+,In_Frame_Del,DEL,GAG,...,False,0.0,NaN,other non-conserving,26:0,NaN,NaN,NaN,NaN,NaN
1231278,MAGEA10,4109,37,X,151304068,151304068,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN
1231279,IRAK1,3654,37,X,153283528,153283528,+,Missense_Mutation,SNP,G,...,False,2.0,NaN,other non-conserving,21:0,NaN,NaN,NaN,NaN,NaN

In [30]:
len(pd.unique(dataset.Entrez_Gene_Id))

18745

In [31]:
subset = dataset[['Entrez_Gene_Id', 'DepMap_ID']]

In [32]:
subset

         Entrez_Gene_Id   DepMap_ID
0                 55187  ACH-000001
1                343066  ACH-000001
3                 55219  ACH-000001
4                  7579  ACH-000001
5                  5453  ACH-000001
...                 ...         ...
1231274             733  ACH-002800
1231276          139818  ACH-002800
1231277             331  ACH-002800
1231278            4109  ACH-002800
1231279            3654  ACH-002800

[863547 rows x 2 columns]

In [33]:
subset=pd.crosstab(subset.DepMap_ID, subset.Entrez_Gene_Id)

In [34]:
subset

Entrez_Gene_Id,1,2,9,10,12,13,14,15,16,18,...,100996928,100996939,101055625,101059918,101059953,101060200,101243544,101362076,101730217,101928601
DepMap_ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-000002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-000003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-000004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
ACH-000005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-002511,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-002512,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-002659,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-002687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-002800,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
subset=pd.merge(info, subset, how='inner', on='DepMap_ID')

In [36]:
subset

,DepMap_ID,primary_disease,1,2,9,10,12,13,14,15,...,100996928,100996939,101055625,101059918,101059953,101060200,101243544,101362076,101730217,101928601
0,ACH-000001,Ovarian Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ACH-000002,Leukemia,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ACH-000003,Colon/Colorectal Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ACH-000004,Leukemia,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,ACH-000005,Leukemia,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1754,ACH-002511,Skin Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1755,ACH-002512,Skin Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1756,ACH-002659,Colon/Colorectal Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1757,ACH-002687,Eye Cancer,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1758,ACH-002800,Sarcoma,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
len(subset.index)

1759

In [38]:
#파일 저장
subset.to_csv("Z:/users/songyeon/DrugTargetIdentification/DepMap(22Q1)/CCLE_mutation_counts_ID_PrimarySite_NoSilent.csv", header=True, index=False)